[project]
name = "rpp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dmgbuild>=1.6.5",
    "pyinstaller>=6.14.2",
    "pywebview>=5.4",
]
